In [1]:
import pandas as pd

In [11]:
pd.read_csv('../../Data/TOC/NG_MP_Aut_2024_10_18.txt',sep='\t',skiprows=10)

,Type,Anal.,Sample Name,Sample ID,Result(TOC),Result(TC),Result(IC),Result(NPOC),Result(TN),Unit,Vial,Date / Time,Unnamed: 12
0,Unknown,NPOC/TN,Blank,Blank,NaN,NaN,NaN,0.05343,0.00000,mg/L,0,18/10/2024 13:16:41,NaN
1,Unknown,NPOC/TN,Blank,Blank,NaN,NaN,NaN,0.12360,0.00000,mg/L,0,18/10/2024 13:26:28,NaN
2,Unknown,NPOC/TN,Blank,Blank,NaN,NaN,NaN,0.14890,0.00000,mg/L,0,18/10/2024 13:38:28,NaN
3,Unknown,NPOC/TN,1,NPOC 5ppm,NaN,NaN,NaN,5.48000,0.04557,mg/L,1,18/10/2024 13:53:41,NaN
4,Unknown,NPOC/TN,1,NPOC 10ppm,NaN,NaN,NaN,9.36200,0.00000,mg/L,2,18/10/2024 14:08:53,NaN
5,Unknown,NPOC/TN,1,NPOC 20ppm,NaN,NaN,NaN,19.34000,0.00000,mg/L,3,18/10/2024 14:24:21,NaN
6,Unknown,NPOC/TN,1,NPOC 50ppm,NaN,NaN,NaN,49.38000,0.00000,mg/L,4,18/10/2024 14:37:23,NaN
7,Unknown,NPOC/TN,Blank,Blank,NaN,NaN,NaN,5.79700,0.10780,mg/L,0,18/10/2024 14:51:40,NaN
8,Unknown,NPOC/TN,1,TN 2 ppm,NaN,NaN,NaN,0.39510,1.83400,mg/L,5,18/10/2024 15:07:46,NaN
9,Unknown,NPOC/TN,1,TN 5 ppm,NaN,NaN,NaN,0.35790,4.88300,mg/L,6,18/10/2024 15:23:26,NaN
10,Unknown,NPOC/TN,1,TN 10 ppm,NaN,NaN,NaN,0.28420,10.04000,mg/L,7,18/10/2024 15:39:03,NaN
11,Unknown,NPOC/TN,Blank,Blank,NaN,NaN,NaN,0.79500,1.56200,mg/L,0,18/10/2024 15:54:55,NaN
12,Unknown,NPOC/TN,Untitled,NPOC 5,NaN,NaN,NaN,5.41900,0.00000,mg/L,19,18/10/2024 16:17:32,NaN
13,Unknown,NPOC/TN,Untitled,NPOC 10,NaN,NaN,NaN,9.59000,0.00000,mg/L,20,18/10/2024 16:33:15,NaN
14,Unknown,NPOC/TN,Untitled,NPOC 20,NaN,NaN,NaN,19.02000,0.01523,mg/L,21,18/10/2024 16:50:02,NaN
15,Unknown,NPOC/TN,Untitled,NPOC 50,NaN,NaN,NaN,49.13000,0.00000,mg/L,22,18/10/2024 17:03:29,NaN
16,Unknown,NPOC/TN,Untitled,Blank,NaN,NaN,NaN,5.52500,0.09616,mg/L,0,18/10/2024 17:18:41,NaN
17,Unknown,NPOC/TN,Untitled,MP TOC 1,NaN,NaN,NaN,46.79000,0.76270,mg/L,8,18/10/2024 17:32:08,NaN
18,Unknown,NPOC/TN,1,MP TOC 2,NaN,NaN,NaN,43.28000,0.80380,mg/L,9,18/10/2024 17:52:37,NaN
19,Unknown,NPOC/TN,Blank,Blank,NaN,NaN,NaN,4.80100,0.18740,mg/L,0,18/10/2024 18:06:42,NaN
20,Unknown,NPOC/TN,1,MP TOC 3,NaN,NaN,NaN,71.45000,1.19300,mg/L,10,18/10/2024 18:27:04,NaN
21,Unknown,NPOC/TN,1,MP TOC 4,NaN,NaN,NaN,62.58000,1.29000,mg/L,11,18/10/2024 18:43:32,NaN
22,Unknown,NPOC/TN,Blank,Blank,NaN,NaN,NaN,6.65100,0.24110,mg/L,0,18/10/2024 19:01:50,NaN
23,Unknown,NPOC/TN,1,MP TOC 6,NaN,NaN,NaN,54.00000,2.29000,mg/L,12,18/10/2024 19:20:23,NaN
24,Unknown,NPOC/TN,1,MP TOC 7,NaN,NaN,NaN,54.14000,1.09500,mg/L,13,18/10/2024 19:41:02,NaN
25,Unknown,NPOC/TN,1,MP TOC 9,NaN,NaN,NaN,62.69000,3.61300,mg/L,14,18/10/2024 19:54:22,NaN
26,Unknown,NPOC/TN,Blank,Blank,NaN,NaN,NaN,6.68300,0.57550,mg/L,0,18/10/2024 20:10:16,NaN
27,Unknown,NPOC/TN,1,MP TOC 11,NaN,NaN,NaN,67.34000,1.96600,mg/L,15,18/10/2024 20:31:10,NaN
28,Unknown,NPOC/TN,1,MP TOC 13,NaN,NaN,NaN,49.72000,1.36500,mg/L,16,18/10/2024 20:48:12,NaN
29,Unknown,NPOC/TN,1,MP TOC 14,NaN,NaN,NaN,77.94000,4.43800,mg/L,17,18/10/2024 21:01:50,NaN
30,Unknown,NPOC/TN,1,MP TOC PL,NaN,NaN,NaN,45.51000,0.94070,mg/L,18,18/10/2024 21:15:13,NaN
31,Unknown,NPOC/TN,Blank,Blank,NaN,NaN,NaN,5.26900,0.22090,mg/L,0,18/10/2024 21:29:28,NaN
32,Unknown,NPOC/TN,1,NPOC 5ppm,NaN,NaN,NaN,5.49600,0.00000,mg/L,1,18/10/2024 21:45:07,NaN
33,Unknown,NPOC/TN,1,NPOC 10ppm,NaN,NaN,NaN,10.13000,0.01051,mg/L,2,18/10/2024 21:57:24,NaN
34,Unknown,NPOC/TN,1,NPOC 20ppm,NaN,NaN,NaN,19.05000,0.00000,mg/L,3,18/10/2024 22:12:58,NaN
35,Unknown,NPOC/TN,1,NPOC 50ppm,NaN,NaN,NaN,50.79000,0.00000,mg/L,4,18/10/2024 22:31:41,NaN
36,Unknown,NPOC/TN,Blank,Blank,NaN,NaN,NaN,0.05791,0.00000,mg/L,0,18/10/2024 22:43:21,NaN
37,Unknown,NPOC/TN,1,TN 2 ppm,NaN,NaN,NaN,0.36220,2.10200,mg/L,5,18/10/2024 22:59:50,NaN
38,Unknown,NPOC/TN,1,TN 5 ppm,NaN,NaN,NaN,0.39100,5.36100,mg/L,6,18/10/2024 23:16:12,NaN
39,Unknown,NPOC/TN,1,TN 10 ppm,NaN,NaN,NaN,0.31850,10.77000,mg/L,7,18/10/2024 23:32:09,NaN
40,Unknown,NPOC/TN,Blank,Blank,NaN,NaN,NaN,0.08869,0.00000,mg/L,0,18/10/2024 23:41:34,NaN
41,Unknown,NPOC/TN,Blank,Blank,NaN,NaN,NaN,0.02679,0.00000,mg/L,0,18/10/2024 23:53:12,NaN